export const STRENGTH_GAIN_HP_BONUS = 1.0;
export const STRENGTH_GAIN_HP_REGEN_BONUS = 0.25;
export const AGILITY_GAIN_ATTACK_SPEED_BONUS = 0.5;
export const AGILITY_GAIN_MOVE_SPEED_BONUS = 0.5;
export const INTELLIGENCE_GAIN_MANA_BONUS = 1.0;
export const INTELLIGENCE_GAIN_MANA_REGEN_BONUS = 0.25;
export const PRIMARY_ATTRIBUTE_DAMAGE_BONUS = 1.0;
